### ISSUE TITLE
Metamask not Detected when Dapper browser extension is also installed

### ISSUE THREAD

**Issue by gkunthara** [livepeer/livepeer-monorepo#418] opened 2019-06-04 20:07 UTC
**Describe the bug (required)**
I am currently logged into my metamask account and am unable to access the "My Account" tab on the livepeer website. I still see the message "limited or no connectivity to web3. Please unlock Metamask or another web3 enabled wallet."

**Expected behavior (required)**
The website should recognize me logged into Metamask, and I should be able to go to My Account

**To Reproduce (required)**
1. Login to Metamask
2. Go to Livepeer website

**Device (required):**
 - Device: Macbook Pro
 - OS: macOS Mojave
 - Browser: Chome 
 - Version: Latest
 
**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/9055394/58910008-5559ae80-86c9-11e9-8ac2-1221beabb503.png)

**Additional context (optional)**
I believe the issue is that I have another web3 enabled wallet (dapper wallet). However, I am currently logged out of that wallet, and logged into Metamask. Is there a way to get the livepeer site to recognize Metamask and disregard my dapper wallet?

**Comment by iameli** [comment] 2019-06-04 21:04
Ah, interesting — I'll try and reproduce this with both wallets installed. [Is this the Dapper browser extension you have installed?](https://chrome.google.com/webstore/detail/dapper/pghmmgdinmfblodenlenkcnmndlnffeo?hl=en)

**Comment by iameli** [comment] 2019-06-04 21:07
Yeah, confirmed. I'll do some research but it's not immediately clear to me that there's much we can do in this case — both Metamask and Dapper are providing the Web3 APIs and unless they play nicely amongst themselves we can only access one of them. Sorry! You could work around it by having different Chrome profiles that had different wallets installed or by using a different browser for each wallet.

**Comment by gkunthara** [comment] 2019-06-04 21:22
Interesting, thanks for the prompt response. I'll take a look at potential workarounds, but let me know if you find a good solution!

**Comment by adamsoffer** [comment] 2021-01-19 17:53
Closing since the old explorer is no longer maintained.

**Closed as completed by adamsoffer** 2021-01-19 17:53 UTC
Labels: area: explorer
