### ISSUE TITLE
"Claim Your Earnings" popup's slider shows wrong rounds' numbers

### ISSUE THREAD

**Issue by wordkeepa** [livepeer/livepeer-monorepo#577] opened 2020-02-29 08:37 UTC
**Describe the bug (required)**
Popup's slider shows wrong value on the right side. Can't move the slider to claim all rounds.

**Expected behavior (required)**
Right sliders's value and ability to move slider.

**To Reproduce (required)**
Open app with connection to Metamask.

**Device (required):**
 - Laptop
 - Windows 10 
 - Chrome
 - 80.0.3987.122 (Official Build) (64-bit)
 
**Screenshots (optional)**
Added

**Additional context (optional)**

![image](https://user-images.githubusercontent.com/55933816/75604136-b4efb980-5aa3-11ea-972e-3e4f2a5a05ba.png)

**Comment by halfinflateddarklord** [comment] 2020-03-08 19:19
I encounter the same issue.  Also windows 10 with chrome & metamask.  Is there any other way to claim rewards (other than going one round at a time)?

**Comment by adamsoffer** [comment] 2020-03-08 20:55
@halfinflateddarklord @wordkeepa - will look into this, but I highly recommend you connect to the new explorer. It allows you to batch claim all your earnings at once 👉https://explorer.livepeer.org

![Screen Shot 2020-02-22 at 2 03 31 PM](https://user-images.githubusercontent.com/555740/76171065-ddd81480-615d-11ea-9ccb-9b3a170149cc.png)

**Comment by halfinflateddarklord** [comment] 2020-03-17 01:44
Thanks @adamsoffer.  The problem is that the Claim Earnings link isn't displayed in my browser.  Does the link you showed only appear once I've gone over 100 rounds without claiming?  I'm trying to claim before 100 rounds so I don't lose out.  Running Chrome on windows with Metamask.   And of course I've searched for it on the My Account tab and on the page of the orchestrator that I'm bonded to, but it's not there.

I appreciate the help.

![ExplorerNoClaim](https://user-images.githubusercontent.com/61947720/76813663-0ea7f180-67cf-11ea-96ab-8a8141494b82.JPG)

**Comment by adamsoffer** [comment] 2020-03-17 01:51
Hey @halfinflateddarklord - correct, it only prompts you to claim earnings if it's been over 100 rounds since your last claim. You don't lose out on anything by not claiming. Unclaimed rewards are considered part of your active stake. Claiming is only necessary if it's been over 100 rounds and even then you don't lose out on anything. More info here 👉https://forum.livepeer.org/t/difference-between-reward-and-claimearnings/244

I think we can do a better job making this more clear in the app. Something we'll look into on the design side of things.

**Comment by halfinflateddarklord** [comment] 2020-03-17 02:21
Thanks!

**Comment by adamsoffer** [comment] 2020-05-12 17:22
This has been fixed in the classic explorer.

**Closed as completed by adamsoffer** 2020-05-12 17:22 UTC

**Comment by halfinflateddarklord** [comment] 2020-05-13 01:17
thanks!
