### ISSUE TITLE
Use `stream/current.m3u8` playback endpoint

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#208] opened 2018-09-14 19:01 UTC
**What's the problem? (required)**

There are two problems:

1. The player looks up the most recent job on the blockchain and uses that StreamID to request the stream. However, there are scenarios where the active job on the node is *not* the most recent job. If this happens, the player will not have the correct Stream ID. Related: https://github.com/livepeer/go-livepeer/issues/556

2. Network lookups can be unreliable. Doubly so with the blockchain. Quadruply so with Infura. Hence, it is not uncommon for the StreamID lookup to fail completely. Related: https://github.com/livepeer/livepeerjs/issues/203

**What's the current behavior? (required)**

When this happens, "Broadcaster Offline" is displayed even though the node is processing the stream correctly.

**Do you have any personal experiences dealing with this problem? (optional)**

This has happened a few times with Livepeer.TV.

**Describe a possible solution you've considered (optional)**

Use the `stream/current.m3u8` playback endpoint that has just been merged into goclient master. This will return the node's active stream while avoiding an external lookup. This should also have the benefit of making the player more responsive, eg streams should start playing faster. Related: https://github.com/livepeer/go-livepeer/pull/557

**Comment by Randy1Burrell** [comment] 2018-10-24 14:40
@ya7ya does PR #243 fix this issue?

**Comment by ya7ya** [comment] 2018-10-24 15:15
@Randy1Burrell Yeah. it does 👍

**Comment by Randy1Burrell** [comment] 2018-10-24 20:57
Closing this.

**Comment by Randy1Burrell** [comment] 2018-11-05 18:46
@ya7ya we need stream/current.m3u8 to work with localhost. Please refer #203 for details of the conversation about this.

**Comment by Randy1Burrell** [comment] 2018-11-05 18:46
Reopened because the problem is not yet solved.

**Comment by iameli** [comment] 2019-02-05 01:16
I believe #320 makes this problem irrelevant.

**Comment by iameli** [comment] 2019-02-08 22:50
Obviated by #320

**Closed as completed** 2019-02-08 22:50 UTC
