### ISSUE TITLE
Buffer stalled error on player

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#22] opened 2018-01-17 16:44 UTC
When I request my stream in the player for the first time I often see a buffer stalled error and frag loop loading error as shown below, and the stream will not start. A refresh sometimes fixes it. 

This is in Chrome on OS X.

![screen shot 2018-01-17 at 11 42 23 am](https://user-images.githubusercontent.com/10389/35054890-bc80c16e-fb7b-11e7-9f04-d7b9ed1698bf.png)

**Comment by jozanza** [comment] 2018-01-17 17:35
@dob Can you add some steps to reproduce this issue?

**Comment by dob** [comment] 2018-01-17 21:52
Sure...

1. Visit https://media.livepeer.org/channels/0x5A4a992c26CbA8459Ec0d77f4c66216D2a8Fd18F while I am not broadcasting

2. Start broadcasting via the local node with that address

3. Immediately refresh the player.

4. The player first has a play button in the middle with a black background, then appears entirely blank. The JS console shows the errors shown at this link:

(Note that the JS console does continue to receive segments, but the video won't play, even if I press the play button. Also note that on the next refresh the video does play fine).

https://cl.ly/3a3f3z3m203S

**Comment by jozanza** [comment] 2018-01-18 21:56
Right on. I was totally able to reproduce this locally. After a lot of investigating, I'm pretty sure it's being caused by this issue in hls.js: https://github.com/video-dev/hls.js/pull/1466

Luckily, it looks like it just merged into their `master`branch a few days ago, so I'll see if using their latest distro solve the issue.

**Comment by jozanza** [comment] 2018-01-22 21:34
It seems part of what causes this issue is the availability of the levels (various profiles) when the stream manifest is first requested. Another issue was the hls.js issue referenced above. I updated to a version of hls.js with the fix and rewrote all of the stream handling logic to be far more robust (https://github.com/livepeer/livepeerjs/commit/a1cd9c2d0598a3467a18472737f00491efb72e80).

Unfortunately, it's hard to confirm this issue is solved on testnet because of network instability. It does work well locally though, so I'm going to close this one out, and we can reopen if we find there are still issues related to the client once testnet is a bit more stable.

**Closed as completed by jozanza** 2018-01-22 21:34 UTC
Labels: type: bug, area: player
